stages:
  - test

default:
  image: python:3.10
  before_script:
    - pip3 install -r requirements.txt

test-ex1:
  stage: test
  script:
    - cd socialfsd
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check
    - python3 manage.py test ex1
