default:
  image: ubuntu:22.04
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.10 python3-pip
    - apt -y upgrade
    - pip3 install -r requirements.txt

test-master:
  stage: test
  script:
    - cd socialfsd
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check
