# Generated by Django 5.0 on 2023-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ex1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="Date"),
        ),
        migrations.AddField(
            model_name="post",
            name="view_counter",
            field=models.IntegerField(default=0, verbose_name="View Counter"),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default="", max_length=200, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="", max_length=200, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=200, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=200, verbose_name="Username"),
        ),
    ]
