# Generated by Django 4.1.7 on 2023-12-21 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ex1", "0003_friendship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Friendship",
        ),
    ]
